### ISSUE TITLE
一点关于代码的问题

### ISSUE THREAD

**Issue by Yeahcy1208** [dawenzi098/SFL-Structural-Federated-Learning#2]
您好，我注意到代码中没有关于交通数据集的部分，能否麻烦您提供完整代码呢？非常感谢！

**Comment by dawenzi098** [comment]
README里有数据处理脚本和下载地址。

**Comment by Yeahcy1208** [comment]
感谢您的回复！我在联邦训练交通数据集时遇到了一点问题，想问您的模型和参数是怎么设置的？如果可以，能否发一份原始代码给我，不胜感激！

**Comment by dawenzi098** [comment]
代码已更新适配Pytorch新版本。

**Comment by like-hopeful** [comment]
> 感谢您的回复！我在联邦训练交通数据集时遇到了一点问题，想问您的模型和参数是怎么设置的？如果可以，能否发一份原始代码给我，不胜感激！

请问您后来了解怎么设置模型和参数进行联邦训练交通数据集了吗？方便指点一下吗
